# syntax=docker/dockerfile:1

FROM golang:1.17-alpine
RUN apk add build-base
RUN apk add libwebp-dev
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download
COPY . ./
RUN go build slack/app.go
CMD [ "/app/app" ]